name: ${project.name}
version: ${project.version}
description: ${project.description}
author: regulad

main: xyz.regulad.SimpleInfo.SimpleInfo
api-version: 1.17
depend:
  - PlaceholderAPI
libraries:
  - org.jetbrains:annotations:21.0.1
